### ISSUE TITLE
CircleCI job fails to using image "python:3.7-windowsservercore"

### ISSUE THREAD

**Issue by jtmoon79** [jtmoon79/goto_http_redirect_server#2]
CircleCI [fails to run job](https://app.circleci.com/jobs/github/jtmoon79/goto_http_redirect_server/467) that uses docker image `python:3.7-windowsservercore`.

The console output reads:
```
Build-agent version 1.0.15410-75b89bda (2019-09-13T15:43:07+0000)
Docker Engine Version: 18.09.6
Kernel Version: Linux 0e78b5f7cd6b 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 Linux
Starting container python:3.7-windowsservercore
  image cache not found on this host, downloading python:3.7-windowsservercore
3.7-windowsservercore: Pulling from library/python
no matching manifest for linux/amd64 in the manifest list entries
```

CircleCI job code:
```
  build_install_run__python_3_7_windowsservercore:
    docker:
      - image: python:3.7-windowsservercore
    steps:
      - checkout
      - run:
          name: build, install, and run in Python 3.7 on Windows Server Core
          command: |
            set -ex
            chmod +x ./.circleci/build-install-run.sh  # force +x
            ./.circleci/build-install-run.sh
```
